### ISSUE TITLE
text below circle of the icon

### ISSUE THREAD

**Issue by tounoussiKhalid** [rafalbednarczuk/curved_navigation_bar#23] opened 2019-05-22 10:58 UTC
I am looking to implement this : 
![Screenshot_85](https://user-images.githubusercontent.com/44621176/58169566-95a83e00-7c80-11e9-9b2c-9ffb72290653.png)

**Comment by rafalbednarczuk** [comment] 2019-05-22 22:09
It's not possible with current version of plugin. Feel free to make pull requests.

**Comment by 392354412** [comment] 2019-11-17 15:56
> It's not possible with current version of plugin. Feel free to make pull requests.

Have you implemented this function now?

**Comment by rafalbednarczuk** [comment] 2019-11-18 01:06
> > It's not possible with current version of plugin. Feel free to make pull requests.
> 
> Have you implemented this function now?

No, if you have make pull request

**Comment by josephepia** [comment] 2020-08-19 06:13
hello, haven't you created an alternative yet?

sorry for my English

**Comment by MstrZeroOne** [comment] 2020-11-17 10:08
> It's not possible with the current version of the plugin. Feel free to make pull requests.

I'm looking for this too. This is 2020/17/November. and this issue is from 2019. Did you add this to the plugin?

**Comment by rafalbednarczuk** [comment] 2020-12-24 12:09
duplicate of https://github.com/rafalbednarczuk/curved_navigation_bar/issues/11

**Closed as completed by rafalbednarczuk** 2020-12-24 12:09 UTC

**Comment by itsahmed-dev** [comment] 2022-08-17 18:01
I did it. Text disappears when you tap the icon.

Add if condition before Text widget and set the condition to index not question to index of that widget in the list as an integer. That's it.

**Comment by Technorocker** [comment] 2022-12-02 13:37
@itsahmed-dev could you share the widget for how you implemented that. I did the condition to index but its still inside the circle and not on the bar itself and when its not selected the text does go away but the icon is shoved up while there is still an "empty" space taking up room.

Thanks ahead of time :)

**Comment by itsahmed-dev** [comment] 2022-12-12 05:19
@Technorocker Here is my widget

```
class CurvedBarItems extends StatelessWidget {
  final int curvedIndex;
  final int index;
  final IconData? icon;
  final String label;
  const CurvedBarItems({
    Key? key,
    required this.index,
    required this.curvedIndex,
    this.icon,
    required this.label,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Icon(icon, size: 30.0),
        if (index != curvedIndex)
          Padding(
            padding: const EdgeInsets.only(top: 8.0),
            child: Text(
              label,
              style: const TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
      ],
    );
  }
}
```

**Comment by Technorocker** [comment] 2023-01-19 21:41
@itsahmed-dev Thank you for sharing. Did you have any problems with the icons being shifted upwards after you used your widget? I implemented it into my navbar but the icons and "shoved" up into the top of the navbar area. I took a screenshot to show you. 

![vext label alignment](https://user-images.githubusercontent.com/35610201/213568069-4860b7a8-cdd6-4e25-a29f-2c37497e13d6.png)

**Comment by itsahmed-dev** [comment] 2023-01-29 07:29
It looks like you can use some padding. Did you try that?

**Comment by Technorocker** [comment] 2023-01-30 12:42
Yes I did thank you, Here is my CurvedBarItems class I ended up with

```
class CurvedBarItems extends StatelessWidget {
  final int curvedIndex;
  final int index;
  final IconData? icon;
  final String label;
  const CurvedBarItems({
    Key? key,
    required this.index,
    required this.curvedIndex,
    this.icon,
    required this.label,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        if (index != curvedIndex) const SizedBox(height: 15),
        Icon(icon, size: index == 1 && curvedIndex == 1 ? 40.0 : 30.0),
        if (index != curvedIndex)
          Padding(
            padding: const EdgeInsets.only(top: 8.0),
            child: Text(
              label,
              style: const TextStyle(
                color: kPrimaryColor,
                fontWeight: FontWeight.bold,
                fontSize: 20,
              ),
            ),
          ),
      ],
    );
  }
}
```

Thanks for the tips.
