### ISSUE TITLE
IN RTL

### ISSUE THREAD

**Issue by AmirAemi** [rafalbednarczuk/curved_navigation_bar#16] opened 2019-04-07 18:23 UTC
I use this in a RTL app and it don't work right

**Comment by Mohammad-ezzidden** [comment] 2019-04-12 23:03
I also have problem when using RTL.

**Comment by rafalbednarczuk** [comment] 2019-04-13 16:18
Please provide sample code and configuration of project with bug.

**Comment by AmmarAl-Wazzan** [comment] 2019-06-01 23:14
hi ...
I used it in the Arabic language ... which is RTL layout ... there is a problem ... 

the problem is when i have 5 items ... and chose the centered item ... ok

but when i chose second items which its index = 1 ... it animated to the mirror position just like i chose the item 4 which its index = 3 .... also the first item (index = 0) look like i choose item 5 (index 4) .... 

`bottomNavigationBar: CurvedNavigationBar(
      index: _page,
      height: 55.0,
      items: <Widget>[
        Icon(Icons.info, size: 25,color: Colors.white,),
        Icon(FontAwesomeIcons.hashtag, size: 22,color: Colors.white,),
        Icon(FontAwesomeIcons.briefcaseMedical, size: 20,color: Colors.white,),        
        Icon(FontAwesomeIcons.solidMoon, size: 20,color: Colors.white,),
        Icon(Icons.account_circle, size: 25,color: Colors.white,),
      ],
      color: Colors.cyan,
      buttonBackgroundColor: Colors.pink,
      backgroundColor: Colors.white,
      animationCurve: Curves.easeInOut,
      animationDuration: Duration(milliseconds: 200),
      onTap: (index) {
        setState(() {
          _page = index;
        });
      },
    )`

Real Example:
 
![Mw6nr (1)](https://user-images.githubusercontent.com/51271352/58754564-a73ce180-84db-11e9-8287-e89a3456264b.jpg)

**Comment by ksamj** [comment] 2019-06-03 16:05
I am facing the same issue 
arabic language is not working and the bar is not working properly 
i have a program in the pipe line depends o this plugin
will be there support ofr the RTL? or i should drop it from the app????

kindly reply ASAP

**Comment by AmmarAl-Wazzan** [comment] 2019-06-03 16:22
@ksamj

The solution here is perfect:
https://github.com/rafalbednarczuk/curved_navigation_bar/pull/26/commits/0a2601f4af2022cc6dea38dc9620606d5b00e077

**Comment by KsAmJ** [comment] 2019-06-03 16:25
> @ksamj
> 
> The solution here is perfect:
> [0a2601f](https://github.com/rafalbednarczuk/curved_navigation_bar/commit/0a2601f4af2022cc6dea38dc9620606d5b00e077)
thanks 
so should i modify it on the source code or you planning to update it on the pub??

**Comment by AmmarAl-Wazzan** [comment] 2019-06-03 16:42
@ksamj 
you welcome
I updated the source code ... and its worded

**Comment by rafalbednarczuk** [comment] 2019-06-03 19:31
wait for final version of RTL support which will be uploaded on pub

**Comment by rafalbednarczuk** [comment] 2019-06-03 20:18
fixed in 
https://github.com/rafalbednarczuk/curved_navigation_bar/commit/a0901e2f57bb6b714eaa8adec6f71fde1bdc5516
pub updated - version 0.2.20

**Closed as completed by rafalbednarczuk** 2019-06-03 20:18 UTC
