### ISSUE TITLE
Bottom nav item flickering while scrolling on iOS

### ISSUE THREAD

**Issue by MohamedRashad99** [rafalbednarczuk/curved_navigation_bar#129] opened 2022-08-19 15:14 UTC
![image](https://user-images.githubusercontent.com/42122633/185650596-ebcd209c-ce32-4047-9729-03de898b9160.png)
![image](https://user-images.githubusercontent.com/42122633/185650660-4c6bb936-6973-42bf-ac7f-61980071fc5b.png)

**Comment by rafalbednarczuk** [comment] 2024-06-03 11:50
duplicate of https://github.com/rafalbednarczuk/curved_navigation_bar/issues/121

**Closed as completed by rafalbednarczuk** 2024-06-03 11:50 UTC
