### ISSUE TITLE
How to make the navbar transparent

### ISSUE THREAD

**Issue by Veerse** [rafalbednarczuk/curved_navigation_bar#54] opened 2020-02-08 19:16 UTC
Hello

Is there any way to make the navbar transparent ?

It doesn't look really good this way... Maybe I'm not using it correctly ?

![Image 08-02-2020 à 20 16](https://user-images.githubusercontent.com/20816459/74090788-dc102800-4aaf-11ea-8fea-46cfe50763a6.jpeg)

**Comment by Inconnu08** [comment] 2020-02-11 18:41
I'm also facing this. Does anybody know if there's a way to make ` backgroundColor` transparent? `backgroundColor: Colors.transparent` does not work...

**Comment by rafalbednarczuk** [comment] 2020-02-11 18:44
duplicate of https://github.com/rafalbednarczuk/curved_navigation_bar/issues/31

**Closed as completed by rafalbednarczuk** 2020-02-11 18:44 UTC

**Comment by itsdani121** [comment] 2021-12-30 05:39
have you found solution?
