### ISSUE TITLE
getting no pubspec.yaml found

### ISSUE THREAD

**Issue by iamkdblue** [rafalbednarczuk/curved_navigation_bar#42] opened 2019-10-31 15:20 UTC
I am getting `curved_navigation_bar/example: no pubspec.yaml found` error.

I searched on net but didn't find any solution:
[https://stackoverflow.com/questions/49786432/how-do-i-fix-no-pubspec-yaml-file-found-in-flutter](url)

**Comment by rafalbednarczuk** [comment] 2019-10-31 15:49
duplicate of https://github.com/rafalbednarczuk/curved_navigation_bar/issues/12
just copy example into your flutter project

**Closed as completed by rafalbednarczuk** 2019-10-31 15:49 UTC
